#
# Copyright (C) 2025 Salvo Giangreco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Debloat list for StardustROM
# - Add entries inside the specific partition containing that file (<PARTITION>_DEBLOAT+="")
# - DO NOT add the partition name at the start of any entry (eg. "/system/dpolicy_system")
# - DO NOT add a slash at the start of any entry (eg. "/dpolicy_system")

# Samsung Defex policy
VENDOR_DEBLOAT+="
etc/dpolicy
"

# Recovery restoration script
VENDOR_DEBLOAT+="
recovery-from-boot.p
bin/install-recovery.sh
etc/init/vendor_flash_recovery.rc
"

# SEPolicy version
VENDOR_DEBLOAT+="
etc/selinux/vendor_sepolicy_version
"

# Apps debloat
PRODUCT_DEBLOAT+="
app
HWRDB/data/hwr_zh_CN.dat
HWRDB/data/hwr_zh_HK.dat
HWRDB/data/hwr_zh_TW.dat
omc/omc_apks_list.txt
omc/single/GLB/res
omc/single/SMA/res
omc/single/XFV/res
preload
etc/init
etc/permissions
etc/sysconfig
priv-app
sipdb/SwiftKey/ar
sipdb/SwiftKey/as
sipdb/SwiftKey/az
sipdb/SwiftKey/be
sipdb/SwiftKey/bg
sipdb/SwiftKey/bn
sipdb/SwiftKey/cs
sipdb/SwiftKey/da
sipdb/SwiftKey/de
sipdb/SwiftKey/el
sipdb/SwiftKey/en_au
sipdb/SwiftKey/en_gb
sipdb/SwiftKey/en_in
sipdb/SwiftKey/es_es
sipdb/SwiftKey/es_us
sipdb/SwiftKey/et
sipdb/SwiftKey/fa
sipdb/SwiftKey/fi
sipdb/SwiftKey/fr_fr
sipdb/SwiftKey/gu
sipdb/SwiftKey/he
sipdb/SwiftKey/hi
sipdb/SwiftKey/hr
sipdb/SwiftKey/hu
sipdb/SwiftKey/hy
sipdb/SwiftKey/id
sipdb/SwiftKey/is
sipdb/SwiftKey/it
sipdb/SwiftKey/jv_id
sipdb/SwiftKey/ka
sipdb/SwiftKey/kk
sipdb/SwiftKey/km
sipdb/SwiftKey/kn
sipdb/SwiftKey/ko
sipdb/SwiftKey/ky
sipdb/SwiftKey/lo
sipdb/SwiftKey/lt
sipdb/SwiftKey/lv
sipdb/SwiftKey/mk
sipdb/SwiftKey/ml
sipdb/SwiftKey/mn
sipdb/SwiftKey/mr
sipdb/SwiftKey/ms
sipdb/SwiftKey/my_mm
sipdb/SwiftKey/my_zg
sipdb/SwiftKey/nb
sipdb/SwiftKey/ne
sipdb/SwiftKey/nl
sipdb/SwiftKey/or
sipdb/SwiftKey/pa
sipdb/SwiftKey/pl
sipdb/SwiftKey/pt_br
sipdb/SwiftKey/pt_pt
sipdb/SwiftKey/ro
sipdb/SwiftKey/ru
sipdb/SwiftKey/si
sipdb/SwiftKey/sk
sipdb/SwiftKey/sl
sipdb/SwiftKey/sq
sipdb/SwiftKey/sr
sipdb/SwiftKey/su_id
sipdb/SwiftKey/sv
sipdb/SwiftKey/szl
sipdb/SwiftKey/ta
sipdb/SwiftKey/te
sipdb/SwiftKey/tg
sipdb/SwiftKey/th
sipdb/SwiftKey/tk
sipdb/SwiftKey/tl
sipdb/SwiftKey/tr
sipdb/SwiftKey/uk
sipdb/SwiftKey/ur
sipdb/SwiftKey/uz
sipdb/SwiftKey/vi
sipdb/Xt9
"

SYSTEM_DEBLOAT+="
system/app/AASAservice
system/app/AddOnComposer
system/app/AllShareAware
system/app/AllshareFileShare
system/app/AllshareMediaShare
system/app/AntHalService
system/app/ANTPlusPlugins
system/app/ANTPlusTest
system/app/ApexService
system/app/AppLinker
system/app/ARCore
system/app/ARDrawing
system/app/ARZone
system/app/AutomationTest_FB
system/app/BasicDreams
system/app/BBCAgent
system/app/BCService
system/app/BGMProvider
system/app/BixbyWakeup
system/app/BluetoothMidiService
system/app/BookmarkProvider
system/app/BrightnessBackupService
system/app/Cameralyzer
system/app/CarrierDefaultApp
system/app/Chrome
system/app/ChromeCustomizations
system/app/com.google.mainline.telemetry
system/app/CtsShimPrebuilt
system/app/DAAgent
system/app/DRParser
system/app/DictDiotekForSec
system/app/DsmsAPK
system/app/DuoStub
system/app/EasterEgg
system/app/EasymodeContactsWidget81
system/app/EdmSimPinService
system/app/EmergencyLauncher
system/app/EmergencyModeService
system/app/EmergencyProvider
system/app/ESEServiceAgent
system/app/Facebook_stub
system/app/FactoryCameraFB
system/app/Fast
system/app/FBAppManager_NS
system/app/Foundation
system/app/GalaxyResourceUpdater
system/app/GearManagerStub
system/app/Gmail2
system/app/GoogleCalendarSyncAdapter
system/app/GoogleLocationHistory
system/app/GooglePrintRecommendationService
system/app/HandwritingService
system/app/HiyaService
system/app/KidsHome_Installer
system/app/LinkSharing_v11
system/app/LiveDrawing
system/app/Maps
system/app/MAPSAgent
system/app/MdecService
system/app/MDMApp
system/app/MdxKitService
system/app/MinusOnePage
system/app/Netflix_activationCommon
system/app/Netflix_stub
system/app/Notes40
system/app/PartnerBookmarksProvider
system/app/Personalization
system/app/PhotoTable
system/app/PlayAutoInstallConfig
system/app/PrintSpooler
system/app/Privacy
system/app/RcsSettings
system/app/SafetyInformation
system/app/SamsungCalendar
system/app/SamsungOne
system/app/SamsungPassAutofill_v1
system/app/SamsungTTS
system/app/SCPMClient
system/app/SecFactoryPhoneTest
system/app/ShortcutBackupService
system/app/SilentLog
system/app/SLocation
system/app/SmartReminder
system/app/SmartSwitchAgent
system/app/SPdfNote
system/app/SpeechServicesByGoogle
system/app/StickerCenter
system/app/Stk
system/app/Stk2
system/app/sveservice
system/app/TEEgrisTuiService
system/app/UnifiedWFC
system/app/UniversalMDMClient
system/app/USBSettings
system/app/VideoEditorLite_Dream_N
system/app/VideoTrimmer
system/app/VisionIntelligence3.7
system/app/VTCameraSetting
system/app/WebManual
system/app/WifiGuider
system/app/WlanTest
system/app/YouTube
system/etc/additional_skipping_apk_list.xml
system/etc/aer_product_name.xml
system/etc/appmanager.conf
system/etc/init/samsung_pass_authenticator_service.rc
system/etc/linkedin.conf
system/etc/msft.preinstall.properties
system/etc/netflixchid.conf
system/etc/Office.conf
system/etc/permissions/com.samsung.bbc.xml
system/etc/permissions/com.samsung.feature.aremoji_v2.xml
system/etc/permissions/com.samsung.feature.ipsgeofence.xml
system/etc/permissions/com.samsung.feature.samsungpositioning.xml
system/etc/permissions/com.samsung.feature.samsung_experience_mobile.xml
system/etc/permissions/privapp-permissions-com.microsoft.appmanager.xml
system/etc/permissions/privapp-permissions-com.samsung.android.app.omcagent.xml
system/etc/permissions/privapp-permissions-com.samsung.android.app.sharelive.xml
system/etc/permissions/privapp-permissions-com.samsung.android.app.smartwidget.xml
system/etc/permissions/privapp-permissions-com.samsung.android.app.tips.xml
system/etc/permissions/privapp-permissions-com.samsung.android.app.updatecenter.xml
system/etc/permissions/privapp-permissions-com.samsung.android.appseparation.xml
system/etc/permissions/privapp-permissions-com.samsung.android.ardrawing.xml
system/etc/permissions/privapp-permissions-com.samsung.android.aremoji.xml
system/etc/permissions/privapp-permissions-com.samsung.android.arzone.xml
system/etc/permissions/privapp-permissions-com.samsung.android.authfw.xml
system/etc/permissions/privapp-permissions-com.samsung.android.beaconmanager.xml
system/etc/permissions/privapp-permissions-com.samsung.android.bixby.agent.xml
system/etc/permissions/privapp-permissions-com.samsung.android.bixby.service.xml
system/etc/permissions/privapp-permissions-com.samsung.android.bixby.wakeup.xml
system/etc/permissions/privapp-permissions-com.samsung.android.cidmanager.xml
system/etc/permissions/privapp-permissions-com.samsung.android.CMFAFramework.xml
system/etc/permissions/privapp-permissions-com.samsung.android.dqagent.xml
system/etc/permissions/privapp-permissions-com.samsung.android.dynamiclock.xml
system/etc/permissions/privapp-permissions-com.samsung.android.easysetup.xml
system/etc/permissions/privapp-permissions-com.samsung.android.fmm.xml
system/etc/permissions/privapp-permissions-com.samsung.android.game.gamehome.xml
system/etc/permissions/privapp-permissions-com.samsung.android.game.gametools.xml
system/etc/permissions/privapp-permissions-com.samsung.android.game.gos.xml
system/etc/permissions/privapp-permissions-com.samsung.android.ipsgeofence.xml
system/etc/permissions/privapp-permissions-com.samsung.android.livestickers.xml
system/etc/permissions/privapp-permissions-com.samsung.android.mateagent.xml
system/etc/permissions/privapp-permissions-com.samsung.android.mcfds.xml
system/etc/permissions/privapp-permissions-com.samsung.android.mcfserver.xml
system/etc/permissions/privapp-permissions-com.samsung.android.mdagent.xml
system/etc/permissions/privapp-permissions-com.samsung.android.mdx.xml
system/etc/permissions/privapp-permissions-com.samsung.android.networkdiagnostic.xml
system/etc/permissions/privapp-permissions-com.samsung.android.providers.factory.xml
system/etc/permissions/privapp-permissions-com.samsung.android.rubin.app.xml
system/etc/permissions/privapp-permissions-com.samsung.android.samsungpass.xml
system/etc/permissions/privapp-permissions-com.samsung.android.samsungpositioning.xml
system/etc/permissions/privapp-permissions-com.samsung.android.sdm.config.xml
system/etc/permissions/privapp-permissions-com.samsung.android.sm.devicesecurity_v6.xml
system/etc/permissions/privapp-permissions-com.samsung.android.smartsuggestions.xml
system/etc/permissions/privapp-permissions-com.samsung.android.smartswitchassistant.xml
system/etc/permissions/privapp-permissions-com.samsung.android.spayfw.xml
system/etc/permissions/privapp-permissions-com.samsung.android.tadownloader.xml
system/etc/permissions/privapp-permissions-com.samsung.android.visionintelligence_v3.7.xml
system/etc/permissions/privapp-permissions-com.samsung.cmfa.AuthTouch.xml
system/etc/permissions/privapp-permissions-com.samsung.cmh.xml
system/etc/permissions/privapp-permissions-com.samsung.crane.xml
system/etc/permissions/privapp-permissions-com.samsung.ipservice.xml
system/etc/permissions/privapp-permissions-com.samsung.klmsagent.xml
system/etc/permissions/privapp-permissions-com.samsung.sec.android.application.csc.xml
system/etc/permissions/privapp-permissions-com.samsung.storyservice.xml
system/etc/permissions/privapp-permissions-com.samsung.systemui.bixby2.xml
system/etc/permissions/privapp-permissions-com.sec.android.app.dexonpc.xml
system/etc/permissions/privapp-permissions-com.sec.android.app.factorykeystring.xml
system/etc/permissions/privapp-permissions-com.sec.android.app.hwmoduletest.xml
system/etc/permissions/privapp-permissions-com.sec.android.app.magnifier.xml
system/etc/permissions/privapp-permissions-com.sec.android.app.myfiles.xml
system/etc/permissions/privapp-permissions-com.sec.android.app.safetyassurance.xml
system/etc/permissions/privapp-permissions-com.sec.android.app.servicemodeapp.xml
system/etc/permissions/privapp-permissions-com.sec.android.app.shealth.xml
system/etc/permissions/privapp-permissions-com.sec.android.daemonapp.xml
system/etc/permissions/privapp-permissions-com.sec.android.diagmonagent.xml
system/etc/permissions/privapp-permissions-com.sec.android.mimage.autodoodle.service.xml
system/etc/permissions/privapp-permissions-com.sec.android.RilServiceModeApp.xml
system/etc/permissions/privapp-permissions-com.sec.android.soagent.xml
system/etc/permissions/privapp-permissions-com.sec.app.RilErrorNotifier.xml
system/etc/permissions/privapp-permissions-com.sec.epdgtestapp.xml
system/etc/permissions/privapp-permissions-com.sec.factory.xml
system/etc/permissions/privapp-permissions-com.sec.imslogger.xml
system/etc/permissions/privapp-permissions-com.sec.location.nsflp2_v6_0.xml
system/etc/permissions/privapp-permissions-com.sec.spp.push.xml
system/etc/permissions/privapp-permissions-com.skms.android.agent.xml
system/etc/permissions/privapp-permissions-com.wsomacp.xml
system/etc/permissions/privapp-permissions-com.wssyncmldm.xml
system/etc/permissions/privapp-permissions-de.axelspringer.yana.zeropage.xml
system/etc/permissions/privapp-permissions-facebook.xml
system/etc/permissions/shealth_sw_pedometer_paused.xml
system/etc/permissions/turboapk-permissions.xml
system/etc/preferred-apps
system/etc/spotify.conf
system/hidden
system/media/audio/notifications
system/media/audio/ringtones
system/media/audio/ui/camera_focus.ogg
system/media/audio/ui/Effect_Tick.ogg
system/media/audio/ui/Dialer_new.ogg
system/media/audio/ui/KeypressDelete.ogg
system/media/audio/ui/KeypressInvalid_1.ogg
system/media/audio/ui/KeypressReturn.ogg
system/media/audio/ui/KeypressSpacebar.ogg
system/media/audio/ui/KeypressStandard.ogg
system/media/audio/ui/SideSync_Connected.ogg
system/media/audio/ui/simple_ripple_down.ogg
system/media/audio/ui/simple_ripple_up.ogg
system/media/audio/ui/WirelessChargingStarted.ogg
system/preload
system/priv-app/AndroidAutoStub
system/priv-app/ANTRadioService
system/priv-app/AppUpdateCenter
system/priv-app/AREmoji
system/priv-app/AuthFactorTouchService
system/priv-app/AuthFramework
system/priv-app/AutoDoodle
system/priv-app/BackupRestoreConfirmation
system/priv-app/BeaconManager
system/priv-app/Bixby
system/priv-app/BixbyService
system/priv-app/BuiltInPrintService
system/priv-app/CallLogBackup
system/priv-app/CarrierWifi
system/priv-app/CellBroadcastServiceModulePlatform
system/priv-app/CIDManager
system/priv-app/CMHProvider
system/priv-app/ConfigUpdater
system/priv-app/ContainerAgent3
system/priv-app/Crane
system/priv-app/CSC
system/priv-app/DevGPUDriver-EX9825
system/priv-app/DeviceKeystring
system/priv-app/DevicePersonalizationServices
system/priv-app/DeviceQualityAgent3
system/priv-app/DeviceTest
system/priv-app/DeXonPC
system/priv-app/DiagMonAgent8
system/priv-app/DigitalWellbeing
system/priv-app/DynamicLockscreen
system/priv-app/DynamicSystemInstallationService
system/priv-app/EasySetup
system/priv-app/EnhancedAttestationAgent
system/priv-app/FaceService
system/priv-app/FactoryTestProvider
system/priv-app/FBInstaller_NS
system/priv-app/FBServices
system/priv-app/Fmm
system/priv-app/FotaAgent
system/priv-app/GalaxyApps_OPEN
system/priv-app/GameHome
system/priv-app/GameOptimizingService
system/priv-app/GameTools_Dream
system/priv-app/GoogleOneTimeInitializer
system/priv-app/GooglePartnerSetup
system/priv-app/GoogleRestore
system/priv-app/GpuWatchApp
system/priv-app/HotwordEnrollmentOKGoogleExCORTEXM4
system/priv-app/HotwordEnrollmentXGoogleExCORTEXM4
system/priv-app/HwModuleTest
system/priv-app/ImsLogger
system/priv-app/IPService
system/priv-app/IpsGeofence
system/priv-app/KLMSAgent
system/priv-app/LinkToWindowsService
system/priv-app/LiveStickers
system/priv-app/LocalTransport
system/priv-app/MateAgent
system/priv-app/MCFDeviceSync
system/priv-app/MdAgent
system/priv-app/MobileWips
system/priv-app/ModemServiceMode
system/priv-app/NetworkDiagnostic
system/priv-app/NSDSWebApp
system/priv-app/NSFusedLocation_v6.0
system/priv-app/OmaCP
system/priv-app/OMCAgent5
system/priv-app/OneDrive_Samsung_v3
system/priv-app/PaymentFramework
system/priv-app/PeripheralFramework
system/priv-app/PhoneErrService
system/priv-app/PrivateComputeServices
system/priv-app/Routines
system/priv-app/RubinVersion3
system/priv-app/SamsungBilling
system/priv-app/SamsungCalendarProvider
system/priv-app/SamsungCloudClient
system/priv-app/SamsungExperienceService
system/priv-app/SamsungMagnifier3
system/priv-app/SamsungMultiConnectivity
system/priv-app/SamsungPass
system/priv-app/SamsungPositioning
system/priv-app/SamsungSmartSuggestions
system/priv-app/SDMConfig
system/priv-app/SecAppSeparation
system/priv-app/SecMyFiles2020
system/priv-app/SendHelpMessage
system/priv-app/serviceModeApp_FB
system/priv-app/SettingsBixby
system/priv-app/SharedStorageBackup
system/priv-app/ShareLive
system/priv-app/SKMSAgent
system/priv-app/SmartCallProvider
system/priv-app/SmartEpdgTestApp
system/priv-app/SmartEye
system/priv-app/SmartManager_v6_DeviceSecurity
system/priv-app/SmartSwitchAssistant
system/priv-app/SmartThingsKit
system/priv-app/SmartWidget
system/priv-app/SOAgent7
system/priv-app/SPPPushClient
system/priv-app/StickerFaceARAvatar
system/priv-app/StoryService
system/priv-app/SVCAgent
system/priv-app/SVoiceIME
system/priv-app/SystemUIBixby2
system/priv-app/TADownloader
system/priv-app/Tag
system/priv-app/TalkbackSE
system/priv-app/TaPackAuthFw
system/priv-app/Traceur
system/priv-app/Turbo
system/priv-app/Upday
system/priv-app/Velvet
system/priv-app/YourPhone_P1_5
system/system_ext/overlay/CellBroadcastConfigOverlayPlatform.apk
system/system_ext/overlay/CellBroadcastServiceOverlay.apk
system/system_ext/overlay/GmsConfigOverlayPhotos.apk
system/system_ext/overlay/GoogleDocumentsUIOverlay.apk
system/system_ext/priv-app/CarrierConfig
system/system_ext/priv-app/CellBroadcastAppPlatform
system/system_ext/priv-app/GoogleFeedback
system/system_ext/priv-app/SetupWizard
system/tts
system/usr/hyphen-data
"
